# Generated by Django 3.0.8 on 2020-07-19 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_auto_20200718_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 13, 33, 16, 972945)),
        ),
    ]
